### ISSUE TITLE
unmount 自定义组件，偶尔失败

### ISSUE THREAD

**Issue by fanyo190** [cas-bigdatalab/piflow#32]
后台频繁出现：Java.lang.NoClassDefFountError:Could not initialize class sun.awt.X11GraphicsEnvironment的错误，重启server可以解决
![image](https://user-images.githubusercontent.com/14494673/102450318-0daf3380-4071-11eb-98d4-3f810e761fe6.png)

**Comment by judy0131** [comment]
尝试在环境变量里添加一下：export DISPLAY=
