### ISSUE TITLE
docker部署web访问api的ip地址是docker容器的内网，外部网络不能直接访问

### ISSUE THREAD

**Issue by longzifan** [cas-bigdatalab/piflow#37]
![微信图片_20210114160521](https://user-images.githubusercontent.com/30691969/104561448-624eca00-5682-11eb-961f-f52f3168fdac.png)

解决方案是进入容器内部，修改启动文件start,sh。$ip_addr直接换成公网地址或者宿主机地址

**Comment by judy0131** [comment]
可以使用端口映射来启动docker：docker run --name piflow -it [imageID] -p 6001:6001 -p 6002:6002

**Comment by judy0131** [comment]
docker pull registry.cn-hangzhou.aliyuncs.com/cnic_piflow/piflow:v0.9.1
docker run -h master -itd --env HOST_IP=*.*.*.* --name piflow-v0.9.1 -p 6001:6001 -p 6002:6002 [imageID]
