### ISSUE TITLE
配置数据源JDBC的driver应该填什么

### ISSUE THREAD

**Issue by cristianoKaKa** [cas-bigdatalab/piflow#38]
文档里mysqlRead的设置里面并没有driver这个选项，但是实际配置mysqlRead和JDBC数据源都要写入driver配置。
尝试过写服务器中的driver路径以及driver文件名(mysql-connector-java)，但都显示为java.lang.ClassNotFounderror

**Comment by cristianoKaKa** [comment]
已解决 填写com.mysql.jdbc.Driver

**Comment by judy0131** [comment]
请问您使用的哪个版本，driver应该输入com.mysql.jdbc.Driver。但是具体mysql的driver jar需要您上传至spark对应目录下。如果使用0.9版本可以通过以下方式上传。



xiaojie.zhu@163.com
 
发件人： cristianoKaKa
发送时间： 2021-01-25 16:47
收件人： cas-bigdatalab/piflow
抄送： Subscribed
主题： [cas-bigdatalab/piflow] 配置数据源JDBC的driver应该填什么 (#38)
文档里mysqlRead的设置里面并没有driver这个选项，但是实际配置mysqlRead和JDBC数据源都要写入driver配置。
尝试过写服务器中的driver路径以及driver文件名(mysql-connector-java)，但都显示为java.lang.ClassNotFounderror

**Comment by cristianoKaKa** [comment]
> 请问您使用的哪个版本，driver应该输入com.mysql.jdbc.Driver。但是具体mysql的driver jar需要您上传至spark对应目录下。如果使用0.9版本可以通过以下方式上传。 xiaojie.zhu@163.com 发件人： cristianoKaKa 发送时间： 2021-01-25 16:47 收件人： cas-bigdatalab/piflow 抄送： Subscribed 主题： [cas-bigdatalab/piflow] 配置数据源JDBC的driver应该填什么 (#38) 文档里mysqlRead的设置里面并没有driver这个选项，但是实际配置mysqlRead和JDBC数据源都要写入driver配置。 尝试过写服务器中的driver路径以及driver文件名(mysql-connector-java)，但都显示为java.lang.ClassNotFounderror — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是0.9版本，使用com.mysql.jdbc.Driver以解决问题
