### ISSUE TITLE
Where is the initialization file for the database?

### ISSUE THREAD

**Issue by yinhedaidi** [cas-bigdatalab/piflow#4]
I installed and started to log in, I can't log in. I got the error message because I didn't create the related database table. How can I initialize the database?

**Comment by sosoll7** [comment]
> I installed and started to log in, I can't log in. I got the error message because I didn't create the related database table. How can I initialize the database?

Hi,Please go here and download the configuration files needed for deployment, which are described in detail.

**Comment by s3ann** [comment]
Hi,where is the SQL script？please

**Comment by sosoll7** [comment]
@s3ann 
Hi,There are SQL scripts in the distribution package. 
Download address:
https://github.com/cas-bigdatalab/piflow-web/releases/tag/0.5

**Comment by s3ann** [comment]
@sosoll7 Oh..hhhhh...thx
